# Generated by Django 5.1.6 on 2025-02-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alumni_careerservice_course_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='transport/')),
            ],
        ),
    ]
