# Generated by Django 5.1.6 on 2025-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_libraryresource_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
