# Generated by Django 5.1.6 on 2025-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_booking_admin_comments_alter_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
