# Generated by Django 5.1.6 on 2025-02-20 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_rename_manifesto_candidate_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
