# Generated by Django 5.1.6 on 2025-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_election_nomination_end_date_nomination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='manifesto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
