# Generated by Django 5.1.6 on 2025-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_address_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_requests',
            field=models.TextField(blank=True),
        ),
    ]
